### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by VR-Punk** [ksooo/service.kodi-fritzbox-callmonitor#3]
Great Work !!! Congratulations !!!

How can i configure the timeout to 60 seconds and nearly fullscreen popup (4K Display) with picture of the fritz!box phone book ?

I can't find it in the source code.

How can i build (compile) the zip file with these settings ?

greets
vr-punk

**Comment by ksooo** [comment]
I’m no longer actively maintaining this addon, sorry, despite from bug fixes.

There is another addon which does basically the same (and more). Maybe you can try this one. 

https://github.com/b-jesch/service.fritzbox.callmonitor
